const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //admin
  ADMIN_LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",

  //user
  ADD_USER_START: "ADD_USER_START",
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  ADD_USER_FAIL: "ADD_USER_FAIL",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "ADMIN_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  //admin
  //gender
  FETCH_GENDER_START: "FETCH_GENDER_START",
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAIL: "FETCH_GENDER_FAIL",

  //position
  FETCH_POSITION_START: "FETCH_POSITION_START",
  FETCH_POSITION_SUCCESS: "FETCH_POSITION_SUCCESS",
  FETCH_POSITION_FAIL: "FETCH_POSITION_FAIL",

  //role
  FETCH_ROLE_START: "FETCH_ROLE_START",
  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAIL: "FETCH_ROLE_FAIL",

  //get all user
  FETCH_ALL_USER_START: "FETCH_ALL_USER_START",
  FETCH_ALL_USER_SUCCESS: "FETCH_ALL_USER_SUCCESS",
  FETCH_ALL_USER_FAIL: "FETCH_ALL_USER_FAIL",

  //delete all user
  DELETE_USER_START: "DELETE_USER_START",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAIL: "DELETE_USER_FAIL",

  //edit all user
  EDIT_USER_START: "EDIT_USER_START",
  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAIL: "EDIT_USER_FAIL",

  //get top doctor
  FETCH_TOP_DOCTOR_START: "FETCH_TOP_DOCTOR_START",
  FETCH_TOP_DOCTOR_SUCCESS: "FETCH_TOP_DOCTOR_SUCCESS",
  FETCH_TOP_DOCTOR_FAIL: "FETCH_TOP_DOCTOR_FAIL",

  //get all doctor
  FETCH_ALL_DOCTOR_START: "FETCH_ALL_DOCTOR_START",
  FETCH_ALL_DOCTOR_SUCCESS: "FETCH_ALL_DOCTOR_SUCCESS",
  FETCH_ALL_DOCTOR_FAIL: "FETCH_ALL_DOCTOR_FAIL",

  //fetch allcode by type
  FETCH_ALLCODE_START: "FETCH_ALLCODE_START",
  FETCH_ALLCODE_SUCCESS: "FETCH_ALLCODE_SUCCESS",
  FETCH_ALLCODE_FAIL: "FETCH_ALLCODE_FAIL",

  //save detail doctor
  SAVE_DETAIL_DOCTOR_START: "SAVE_DETAIL_DOCTOR_START",
  SAVE_DETAIL_DOCTOR_SUCCESS: "SAVE_DETAIL_DOCTOR_SUCCESS",
  SAVE_DETAIL_DOCTOR_FAIL: "SAVE_DETAIL_DOCTOR_FAIL",

  //get detail doctor
  GET_DETAIL_DOCTOR_START: "GET_DETAIL_DOCTOR_START",
  GET_DETAIL_DOCTOR_SUCCESS: "GET_DETAIL_DOCTOR_SUCCESS",
  GET_DETAIL_DOCTOR_FAIL: "GET_DETAIL_DOCTOR_FAIL",

  //get schedule allcodes
  FETCH_ALLCODE_SCHEDULE_HOURS_START: "FETCH_ALLCODE_SCHEDULE_HOURS_START",
  FETCH_ALLCODE_SCHEDULE_HOURS_SUCCESS: "FETCH_ALLCODE_SCHEDULE_HOURS_SUCCESS",
  FETCH_ALLCODE_SCHEDULE_HOURS_FAIL: "FETCH_ALLCODE_SCHEDULE_HOURS_FAIL",

  //save schedule allcodes
  SAVE_ALLCODE_SCHEDULE_HOURS_START: "SAVE_ALLCODE_SCHEDULE_HOURS_START",
  SAVE_ALLCODE_SCHEDULE_HOURS_SUCCESS: "SAVE_ALLCODE_SCHEDULE_HOURS_SUCCESS",
  SAVE_ALLCODE_SCHEDULE_HOURS_FAIL: "SAVE_ALLCODE_SCHEDULE_HOURS_FAIL",

  //GET schedule doctor by date
  GET_SCHEDULE_DOCTOR_BY_DATE_START: "GET_SCHEDULE_DOCTOR_BY_DATE_START",
  GET_SCHEDULE_DOCTOR_BY_DATE_SUCCESS: "GET_SCHEDULE_DOCTOR_BY_DATE_SUCCESS",
  GET_SCHEDULE_DOCTOR_BY_DATE_FAIL: "GET_SCHEDULE_DOCTOR_BY_DATE_FAIL",

  //GET extra info doctor by id
  GET_EXTRA_INFO_DOCTOR_BY_ID_START: "GET_EXTRA_INFO_DOCTOR_BY_ID_START",
  GET_EXTRA_INFO_DOCTOR_BY_ID_SUCCESS: "GET_EXTRA_INFO_DOCTOR_BY_ID_SUCCESS",
  GET_EXTRA_INFO_DOCTOR_BY_ID_FAIL: "GET_EXTRA_INFO_DOCTOR_BY_ID_FAIL",

  //book an appointment with doctor
  BOOK_APPOINTMENT_WITH_DOCTOR_START: "BOOK_APPOINTMENT_WITH_DOCTOR_START",
  BOOK_APPOINTMENT_WITH_DOCTOR_SUCCESS: "BOOK_APPOINTMENT_WITH_DOCTOR_SUCCESS",
  BOOK_APPOINTMENT_WITH_DOCTOR_FAIL: "BOOK_APPOINTMENT_WITH_DOCTOR_FAIL",

  //get all special
  GET_ALL_SPECIALTY_START: "GET_ALL_SPECIALTY_START",
  GET_ALL_SPECIALTY_SUCCESS: "GET_ALL_SPECIALTY_SUCCESS",
  GET_ALL_SPECIALTY_FAIL: "GET_ALL_SPECIALTY_FAIL",
});

export default actionTypes;
